site_name: Hongnan G. Machine Learning Blog
site_url: https://reighns92.github.io/reighns-ml-blog
nav:
  - Home: index.md
  - About: about.md
  # - Getting Started: 
  #   - Workflow: getting_started.md
  # - Misc:
  #   - GCP: misc/gcp.md
  - Software Engineering Practices: 
    - Git: reighns_ml_journey/software_engineering/git.md
  - Mathematics:
    - General Mathematic Terms and Definitions: reighns_ml_journey/mathematics/general_mathematical_terms_and_definitions.md
    - Linear Algebra:
      - Preliminaries: 
        - Lines and Planes: reighns_ml_journey/mathematics/linear_algebra/01_preliminaries/lines_and_planes.md
        - Fields: reighns_ml_journey/mathematics/linear_algebra/01_preliminaries/fields.md
      - Vectors:
        - Vector Operations: reighns_ml_journey/mathematics/linear_algebra/02_vectors/02_linear_algebra_vectors.md
        - Vector Products:
          - Linear Combination: reighns_ml_journey/mathematics/linear_algebra/02_vectors/02_linear_algebra_vectors_linear_combination.md
          - Dot Product: reighns_ml_journey/mathematics/linear_algebra/02_vectors/02_linear_algebra_vectors_dot_product.md
          - Outer Product: reighns_ml_journey/mathematics/linear_algebra/02_vectors/02_linear_algebra_vectors_outer_product.md
          - Unit Vector: reighns_ml_journey/mathematics/linear_algebra/02_vectors/02_linear_algebra_vectors_unit_vector.md
          - Exercises: reighns_ml_journey/mathematics/linear_algebra/02_vectors/02_linear_algebra_vectors_exercises.md
      - Vector Spaces: 
        - Vector Space and Subspaces: reighns_ml_journey/mathematics/linear_algebra/03_vector_spaces/03_linear_algebra_vector_spaces_vector_subspaces.md
        - Vector Span: reighns_ml_journey/mathematics/linear_algebra/03_vector_spaces/03_linear_algebra_vector_spaces_vector_span.md
        - Linear Independence: reighns_ml_journey/mathematics/linear_algebra/03_vector_spaces/03_linear_algebra_vector_spaces_linear_independence.md
        - Basis and Dimension: reighns_ml_journey/mathematics/linear_algebra/03_vector_spaces/03_linear_algebra_vector_spaces_basis_dimension.md
      - Matrix:
        - Matrix: reighns_ml_journey/mathematics/linear_algebra/04_matrices/04_linear_algebra_matrix.md
        - Basic Matrix Types: reighns_ml_journey/mathematics/linear_algebra/04_matrices/04_linear_algebra_matrix_basic_matrix_types.md
        - Basic Matrix Operations: reighns_ml_journey/mathematics/linear_algebra/04_matrices/04_linear_algebra_matrix_basic_operations.md
        - Matrix Multiplication: reighns_ml_journey/mathematics/linear_algebra/04_matrices/04_linear_algebra_matrix_multiplication.md
      - Matrix Theory:
        - System of Linear Equations: reighns_ml_journey/mathematics/linear_algebra/05_system_of_linear_equations_and_matrix_theory/05.01_linear_algebra_systems_of_linear_equations.md 
        - Row Reduction Preserves Rank: reighns_ml_journey/mathematics/linear_algebra/05_system_of_linear_equations_and_matrix_theory/05.02_linear_algebra_row_reduction_preserves_rank.md
        - Row Space: reighns_ml_journey/mathematics/linear_algebra/05_system_of_linear_equations_and_matrix_theory/05.03_linear_algebra_matrix_theory_matrix_spaces_row_space.md  
        - Column Space: reighns_ml_journey/mathematics/linear_algebra/05_system_of_linear_equations_and_matrix_theory/05.04_linear_algebra_matrix_theory_matrix_spaces_column_space.md  
        - Right Nullspace (Kernel): reighns_ml_journey/mathematics/linear_algebra/05_system_of_linear_equations_and_matrix_theory/05.05_linear_algebra_matrix_theory_matrix_spaces_right_nullspace.md
        - Left Nullspace: reighns_ml_journey/mathematics/linear_algebra/05_system_of_linear_equations_and_matrix_theory/05.06_linear_algebra_matrix_theory_matrix_spaces_left_nullspace.md
        - Matrix Rank: reighns_ml_journey/mathematics/linear_algebra/05_system_of_linear_equations_and_matrix_theory/05.07_linear_algebra_matrix_theory_matrix_rank.md
        - The Four Fundamental Subspaces (Summary): reighns_ml_journey/mathematics/linear_algebra/05_system_of_linear_equations_and_matrix_theory/05.08_linear_algebra_matrix_theory_matrix_spaces_summary.md
      - Linear Transformation:
        - Linear Transformation: reighns_ml_journey/mathematics/linear_algebra/06_linear_transformation/06.01_linear_algebra_linear_transformations.md
        - Nullspace: reighns_ml_journey/mathematics/linear_algebra/06_linear_transformation/06.02_linear_algebra_linear_transformations_nullspace.md
        - Range: reighns_ml_journey/mathematics/linear_algebra/06_linear_transformation/06.03_linear_algebra_linear_transformations_ranges.md
        - Homomorphism: reighns_ml_journey/mathematics/linear_algebra/06_linear_transformation/06.04_linear_algebra_linear_transformations_homomorphism.md
        - Fundamental Theorem: reighns_ml_journey/mathematics/linear_algebra/06_linear_transformation/06.05_linear_algebra_linear_transformations_fundamental_theorem.md
        - Linear Transformation and Matrix: reighns_ml_journey/mathematics/linear_algebra/06_linear_transformation/06.06_linear_algebra_linear_transformations_matrix.md
      - Analytic Geometry:
        - Orthogonal Subspace: reighns_ml_journey/mathematics/linear_algebra/08_analytic_geometry/08.06_orthogonal_subspaces.md
      - Interview: reighns_ml_journey/mathematics/linear_algebra/linear_algebra_interview_questions.md
    - Probability and Statistics:
      - Introduction to Probability for Data Science (Stanley H. Chan): reighns_ml_journey/mathematics/probability_statistics_theory/probability4datascience.md
      - Introduction to Probability: 
        - Probability Space: reighns_ml_journey/mathematics/probability_statistics_theory/02_introduction_to_probability/02.01_probability_space.md
        - Probability Axioms: reighns_ml_journey/mathematics/probability_statistics_theory/02_introduction_to_probability/02.02_probability_axioms.md
        - Conditional Probability: reighns_ml_journey/mathematics/probability_statistics_theory/02_introduction_to_probability/02.03_conditional_probability.md
        - Independence: reighns_ml_journey/mathematics/probability_statistics_theory/02_introduction_to_probability/02.04_independence.md
        - Bayes' Theorem: reighns_ml_journey/mathematics/probability_statistics_theory/02_introduction_to_probability/02.05_bayes_theorem.md
  - Machine Learning:
    - Machine Learning Metrics: 
      - Classification:
        - Introduction: reighns_ml_journey/machine_learning/metrics/classification_metrics/classification_metrics.md
        - Accuracy: reighns_ml_journey/machine_learning/metrics/classification_metrics/accuracy.md
        - Confusion Matrix: reighns_ml_journey/machine_learning/metrics/classification_metrics/confusion_matrix.md
        - Precision-Recall-F1: reighns_ml_journey/machine_learning/metrics/classification_metrics/precision_recall_f1.md
        - ROC and PR Curves: reighns_ml_journey/machine_learning/metrics/classification_metrics/roc_pr_curve.md
        - Cohen's Kappa: reighns_ml_journey/machine_learning/metrics/classification_metrics/cohens_kappa.md
      - Regression:
        - Introduction: reighns_ml_journey/machine_learning/metrics/regression_metrics/regression_metrics.md
  - Deep Learning:
    - Computer Vision:
      - Neural Network Interpretation: 
        - Visualization of Feature Map Activations: 
          - Feature Map Activations (Part I): reighns_ml_journey/deep_learning/computer_vision/neural_network_interpretation/01_feature_map_activation/feature_map_activation.md
          - Feature Map Activations (Part II): reighns_ml_journey/deep_learning/computer_vision/neural_network_interpretation/01_feature_map_activation/feature_map_activation_reduced.md
        - Visualization of Convolutional Filters: reighns_ml_journey/deep_learning/computer_vision/neural_network_interpretation/conv_filters/Visualizing Convolutional Filters.md
        - Salient Map: reighns_ml_journey/deep_learning/computer_vision/neural_network_interpretation/salient_map/Salient Map.md
        - Grad-CAM:
          - Grad-CAM Explained: reighns_ml_journey/deep_learning/computer_vision/neural_network_interpretation/05_gradcam_and_variants/gradcam_explained.md
          - Grad-CAM from Scratch: reighns_ml_journey/deep_learning/computer_vision/neural_network_interpretation/05_gradcam_and_variants/gradcam_from_scratch.md
      - Image Normalization: reighns_ml_journey/deep_learning/computer_vision/image_normalization/Image_Normalization_and_Standardization.md
    - Fundamental Concepts:
      - Cross Entropy Loss: reighns_ml_journey/deep_learning/fundamentals/loss_functions/cross_entropy_loss/cross_entropy_loss_from_scratch.md
    - Ensemble Theory:
      - Forward Ensemble (Hill Climbing): reighns_ml_journey/deep_learning/ensemble_theory/forward_ensemble.md
  - Data Structures and Algorithms: reighns_ml_journey/data_structures_and_algorithms/data_structures_and_algorithms.md
  - Machine Learning Projects:
      - Breast Cancer Wisconsin (Supervised Classification):
        - Introduction: reighns_ml_journey/projects/breast_cancer_wisconsin/Stage 0 - Introduction and Problem Statement.md
        - Preliminary Data Inspection and Cleaning: reighns_ml_journey/projects/breast_cancer_wisconsin/Stage 1 - Preliminary Data Inspection and Cleaning.md
        - EDA: reighns_ml_journey/projects/breast_cancer_wisconsin/Stage 2 - Preliminary EDA.md
        - Feature Engineering: reighns_ml_journey/projects/breast_cancer_wisconsin/Stage 3 - Feature Engineering.md
        - Modelling (Metrics): reighns_ml_journey/projects/breast_cancer_wisconsin/Stage 4 - Modelling (Metric to Optimize).md
        - Modelling (Cross-Validation Schema): reighns_ml_journey/projects/breast_cancer_wisconsin/Stage 5 - Modelling (Cross-Validation Methodology).md
        - Modelling (Preprocessing and Spot Checking): reighns_ml_journey/projects/breast_cancer_wisconsin/Stage 6 - Modelling (Preprocessing and Spot Checking).md
        - Modelling (Model Selection): reighns_ml_journey/projects/breast_cancer_wisconsin/Stage 7 - Modelling (Model Selection and Hyperparameter Tuning).md
        - Modelling (Model Evaluation): reighns_ml_journey/projects/breast_cancer_wisconsin/Stage 8 - Modelling (Model Evaluation and Interpretation).md
theme:
  name: material
markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascript/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
    - css/extra.css